// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testmodule.proxies;

public enum HeaderFooter
{
	Both(new java.lang.String[][] { new java.lang.String[] { "en_US", "Both" } }),
	Header(new java.lang.String[][] { new java.lang.String[] { "en_US", "Header" } }),
	Footer(new java.lang.String[][] { new java.lang.String[] { "en_US", "Footer" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private HeaderFooter(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
