// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package documentgeneration.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the DocumentGeneration module
	public static void aCT_Registration_Revoke(IContext context, documentgeneration.proxies.Configuration _configuration)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Configuration", _configuration == null ? null : _configuration.getMendixObject());
		Core.microflowCall("DocumentGeneration.ACT_Registration_Revoke").withParams(params).execute(context);
	}
	public static void aCT_Registration_Start(IContext context, documentgeneration.proxies.Configuration _configuration, documentgeneration.proxies.RegistrationWizard _registrationWizard)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Configuration", _configuration == null ? null : _configuration.getMendixObject());
		params.put("RegistrationWizard", _registrationWizard == null ? null : _registrationWizard.getMendixObject());
		Core.microflowCall("DocumentGeneration.ACT_Registration_Start").withParams(params).execute(context);
	}
	public static boolean aSu_DocumentGeneration_Initialize(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.Boolean) Core.microflowCall("DocumentGeneration.ASu_DocumentGeneration_Initialize").withParams(params).execute(context);
	}
	public static documentgeneration.proxies.Configuration dS_Configuration_FindOrCreate(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("DocumentGeneration.DS_Configuration_FindOrCreate").withParams(params).execute(context);
		return result == null ? null : documentgeneration.proxies.Configuration.initialize(context, result);
	}
	public static documentgeneration.proxies.RegistrationWizard dS_RegistrationWizard_FindOrCreate(IContext context, documentgeneration.proxies.Configuration _configuration)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Configuration", _configuration == null ? null : _configuration.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("DocumentGeneration.DS_RegistrationWizard_FindOrCreate").withParams(params).execute(context);
		return result == null ? null : documentgeneration.proxies.RegistrationWizard.initialize(context, result);
	}
	public static void sE_AccessToken_Refresh(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("DocumentGeneration.SE_AccessToken_Refresh").withParams(params).execute(context);
	}
	public static void sE_DocumentRequest_Cleanup(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("DocumentGeneration.SE_DocumentRequest_Cleanup").withParams(params).execute(context);
	}
	public static boolean vAL_Registration_Input(IContext context, documentgeneration.proxies.RegistrationWizard _registrationWizard)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("RegistrationWizard", _registrationWizard == null ? null : _registrationWizard.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("DocumentGeneration.VAL_Registration_Input").withParams(params).execute(context);
	}
}
